# Generated by Django 4.2.5 on 2023-09-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_aluno"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="nome",
            field=models.CharField(default="Nome Padrão", max_length=100),
        ),
    ]
