# Generated by Django 4.2.5 on 2023-09-27 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0005_remove_aluno_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="senha",
            field=models.CharField(default="Digite sua senha aqui", max_length=100),
        ),
        migrations.AddField(
            model_name="aluno",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="nome",
            field=models.CharField(default="Digite seu nome aqui", max_length=100),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="turma",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.turma"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.aluno"
            ),
        ),
    ]
