# Generated by Django 4.2.5 on 2023-09-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_aluno_senha_aluno_user_alter_aluno_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="senha",
            field=models.CharField(max_length=100),
        ),
    ]
