# Generated by Django 4.2.5 on 2023-09-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_aluno_senha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turma",
            name="professor",
        ),
        migrations.AlterField(
            model_name="aluno",
            name="turma",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turmas_aluno",
                to="app.turma",
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="alunos",
            field=models.ManyToManyField(related_name="turmas_turma", to="app.aluno"),
        ),
    ]
