# Generated by Django 4.2.5 on 2023-09-27 23:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_remove_turma_professor_alter_aluno_turma_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="user",
        ),
    ]
