# Generated by Django 4.2.5 on 2023-09-27 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_remove_aluno_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacao",
            name="turma",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.turma"
            ),
        ),
    ]
