# Generated by Django 4.2.5 on 2023-09-28 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_rename_avaliacao_media_avaliacao"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Media_Avaliacao",
            new_name="Avaliacao",
        ),
    ]
