# Generated by Django 4.2.5 on 2023-10-11 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_alter_aluno_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="turma",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="user",
        ),
    ]
