# Generated by Django 4.2.5 on 2023-10-11 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_remove_aluno_turma_remove_aluno_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professor",
            name="user",
        ),
    ]
