# Generated by Django 4.2.5 on 2023-10-12 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_remove_professor_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aula",
            name="data",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="turma",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.turma"
            ),
        ),
    ]
