# Generated by Django 4.2.5 on 2023-10-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_alter_aula_data_alter_avaliacao_turma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="nota",
            field=models.IntegerField(),
        ),
    ]
