# Generated by Django 4.2.5 on 2023-10-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_alter_avaliacao_nota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="nota",
            field=models.FloatField(),
        ),
    ]
